export const projects = [
  {
    id: "lumora",
    index: "01",
    title: "LUMORA",
    subtitle: "Feline Atelier",
    category: "Luxury E-Commerce",
    year: "2025",
    description: "A cinematic, museum-grade e-commerce experience for a modern feline house. Quiet luxury, editorial motion, and obsessive typography.",
    color: "#C9A96E",
    accent: "#F8F3EA",
    image: "/demo-lumora.webp",
    preview: "/demo-lumora.webp",
    tags: ["Next.js", "GSAP", "Shopify"],
    href: "#",
    stats: { pages: "24 Pages", score: "98 Lighthouse", aw: "Awwwards Mention" }
  },
  {
    id: "contrictors",
    index: "02",
    title: "CONTRICTORS",
    subtitle: "Build Group",
    category: "Construction & Real Estate",
    year: "2025",
    description: "Bold, brutalist construction site built to feel like heavy machinery — concrete, steel, and light. Hire us for anything you can imagine.",
    color: "#FF6B1A",
    accent: "#0A0A0B",
    image: "/demo-contrictors.webp",
    preview: "/demo-contrictors.webp",
    tags: ["Next.js", "GSAP", "Sanity"],
    href: "https://webiste1-weld.vercel.app/",
    stats: { pages: "18 Pages", score: "98 Lighthouse", aw: "Editorial Pick" }
  },
  {
    id: "chocobakes",
    index: "03",
    title: "CHOCOBAKES",
    subtitle: "Craving?",
    category: "Food & Beverage",
    year: "2025",
    description: "High-energy ice cream experience with melting chocolate, flying splashes, and a question you can't ignore — HOW?",
    color: "#8B3A14",
    accent: "#3A1F0A",
    image: "/demo-icecream.webp",
    preview: "/demo-icecream.webp",
    tags: ["React", "Framer Motion", "Shopify"],
    href: "#",
    stats: { pages: "16 Pages", score: "99 Lighthouse", aw: "Site of the Day" }
  },
  {
    id: "velmora",
    index: "04",
    title: "VELMORA",
    subtitle: "Juicy",
    category: "Beverage & Lifestyle",
    year: "2025",
    description: "Taste the pink side of life. Fruit drinks made to turn an ordinary sip into something worth remembering.",
    color: "#E85A7A",
    accent: "#4A0F1F",
    image: "/demo-velmora.webp",
    preview: "/demo-velmora.webp",
    tags: ["Next.js", "Three.js", "Prismic"],
    href: "#",
    stats: { pages: "14 Pages", score: "97 Lighthouse", aw: "Featured" }
  },
  {
    id: "zebronix",
    index: "05",
    title: "ZEBRONIX",
    subtitle: "Logistics",
    category: "Industrial & Logistics",
    year: "2025",
    description: "Precision delivery. An orange container suspended mid-air — 99% on time, every time.",
    color: "#FF6B1A",
    accent: "#1A0F00",
    image: "/demo-zebronix.webp",
    preview: "/demo-zebronix.webp",
    tags: ["Next.js", "GSAP", "Headless"],
    href: "#",
    stats: { pages: "20 Pages", score: "98 Lighthouse", aw: "Industrial Pick" }
  },
  {
    id: "comingsoon",
    index: "06",
    title: "COMING SOON",
    subtitle: "",
    category: "Next Project",
    year: "2026",
    description: "Next demo is brewing — stay tuned for the next website concept.",
    color: "#8E9AAF",
    accent: "#070708",
    image: "",
    preview: "",
    tags: ["Coming Soon"],
    href: "#",
    stats: { pages: "—", score: "—", aw: "Stay Tuned" }
  }
];
